'use strict';
const $ = selector => document.querySelector(selector);
const paths = {
 home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',list:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>',chart:'<path d="M4 3v18h17M9 16v-5M14 16V6M19 16v-8"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1M5.6 18.4l2.1-2.1m8.6-8.6 2.1-2.1"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',leaf:'<path d="M20 3C9 2 3 7 5 14s15 5 15-11ZM4 21 15 10"/>',plus:'<path d="M12 5v14M5 12h14"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18M7 15h2m3 0h2"/>',wallet:'<path d="M20 8V5H4a2 2 0 0 0 0 4h17v11H4a2 2 0 0 1-2-2V7"/><path d="M21 12h-6v5h6"/>',down:'<path d="M17 7 7 17M7 7v10h10"/>',up:'<path d="M7 17 17 7M7 7h10v10"/>',trend:'<path d="m3 17 6-6 4 4 8-10M15 5h6v6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',edit:'<path d="m14 5 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>'
};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.list}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el => { el.outerHTML = icon(el.dataset.icon,el.className); });
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen = value => `${value < 0 ? '−' : ''}¥${Math.abs(value).toLocaleString('ja-JP')}`;
const localDate = (date=new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const shiftMonth = (key,delta) => { const [year,month]=key.split('-').map(Number); const d=new Date(year,month-1+delta,1); return localDate(d).slice(0,7); };
const categories = {expense:['食費','日用品','住居費','交通費','光熱費','通信費','医療・健康','衣服・美容','趣味・娯楽','教育','交際費','その他'],income:['給与','賞与','副収入','その他']};
const colors=['#aa95d7','#7ebbad','#e5bd84','#9db4d3','#d9a6b6','#adb4c3'];
let transactions=[],users=[],currentUserId=null,selectedMonth=localDate().slice(0,7),page=1,loaded=false,pendingDelete=null,busy=false,userBusy=false,toastTimer,pendingImageData=null,removeExistingImage=false;
const maxImageBytes=5*1024*1024,allowedImageTypes=['image/jpeg','image/png','image/webp'];
const pageSize=12;
const currentEntries = () => transactions.filter(t=>t.date.startsWith(selectedMonth));
const sum = (list,type) => list.filter(t=>t.type===type).reduce((total,t)=>total+t.amount,0);
const grouped = list => { const result=new Map();list.filter(t=>t.type==='expense').forEach(t=>result.set(t.category,(result.get(t.category)||0)+t.amount));return [...result].sort((a,b)=>b[1]-a[1]); };
const newest = (a,b) => b.date.localeCompare(a.date)||b.id-a.id;
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4000);}
async function api(path,method='GET',data){
 let response;
 try {response=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)});} catch {throw new Error(method==='GET'?'接続できませんでした。サーバーの起動状態を確認してください。':'通信が途切れました。再読み込みで保存状況を確認してから、もう一度操作してください。');}
 if(!response.ok){let error;try{error=await response.json();}catch{}throw new Error(error?.error||'操作を完了できませんでした。もう一度お試しください。');}
 return response.status===204?null:response.json();
}
async function load(){
 $('#retryLoad').disabled=true;
 try{users=await api('/api/users');let stored=0;try{stored=Number(localStorage.getItem('tsumugi-user'));}catch{}currentUserId=users.some(user=>user.id===stored)?stored:users[0].id;transactions=await api(`/api/transactions?userId=${currentUserId}`);loaded=true;$('#loadError').hidden=true;renderUsers();render();$('#syncStatus').textContent='保存済み · このパソコン';}
 catch(error){$('#loadError').hidden=false;$('#loadError span').textContent=error.message;$('#syncStatus').textContent='接続を確認してください';}
 finally{$('#retryLoad').disabled=false;updateAvailability();}
}
function updateAvailability(){['#openEntry','#exportAll','#exportFiltered','#exportReport'].forEach(s=>$(s).disabled=!loaded);}
function currentUser(){return users.find(user=>user.id===currentUserId);}
function renderUsers(){const options=users.map(user=>`<option value="${user.id}">${escapeHtml(user.name)}</option>`).join('');$('#userSwitcher').innerHTML=options;$('#userSwitcher').value=String(currentUserId);$('#userList').innerHTML=users.map(user=>`<div class="user-list-item${user.id===currentUserId?' is-current':''}"><span class="profile-dot">${escapeHtml(user.name.slice(0,1))}</span><span><strong>${escapeHtml(user.name)}</strong><small>${user.id===currentUserId?'選択中':'利用者'}</small></span></div>`).join('');}
function render(){
 $('#monthPicker').value=selectedMonth;$('#previousMonth').disabled=selectedMonth==='1900-01';$('#nextMonth').disabled=selectedMonth==='9999-12';
 const list=currentEntries(),income=sum(list,'income'),expense=sum(list,'expense');
 $('#balanceValue').textContent=yen(income-expense);$('#incomeValue').textContent=yen(income);$('#expenseValue').textContent=yen(expense);
 $('#incomeCount').textContent=`${list.filter(t=>t.type==='income').length}件の収入`;
 $('#expenseCount').textContent=`${list.filter(t=>t.type==='expense').length}件の支出`;
 $('#savingsValue').textContent=income?`${((income-expense)/income*100).toFixed(1)}%`:'—';
 $('#balanceNote').textContent='収入 − 支出 · この月の差し引き';
 $('#recentCount').textContent=list.length;$('#allDataCount').textContent=`${currentUser()?.name||''}・全期間${transactions.length}件`;
 const previousCategory=$('#categoryFilter').value;
 $('#categoryFilter').innerHTML='<option value="">すべてのカテゴリ</option>'+[...new Set(transactions.map(t=>t.category))].sort((a,b)=>a.localeCompare(b,'ja')).map(c=>`<option>${escapeHtml(c)}</option>`).join('');
 $('#categoryFilter').value=[...$('#categoryFilter').options].some(o=>o.value===previousCategory)?previousCategory:'';
 renderChart();renderCategories(list,expense);renderTable('#recentTable',[...list].sort(newest).slice(0,5));renderLedger();renderReport();
}
function renderChart(){
 const months=Array.from({length:6},(_,i)=>{const key=shiftMonth(selectedMonth,i-5),list=transactions.filter(t=>t.date.startsWith(key));return {key,income:sum(list,'income'),expense:sum(list,'expense')};});
 const max=Math.max(10000,...months.flatMap(m=>[m.income,m.expense]));const magnitude=10**Math.floor(Math.log10(max));const ceiling=Math.ceil(max/magnitude)*magnitude;
 let svg=`<svg viewBox="0 0 540 220" role="img" aria-label="過去6か月の収入と支出"><title>${months.map(m=>`${m.key} 収入${yen(m.income)} 支出${yen(m.expense)}`).join('、')}</title>`;
 for(let i=0;i<5;i++){const y=16+i*43;const value=ceiling*(1-i/4);svg+=`<line class="grid-line" x1="55" y1="${y}" x2="535" y2="${y}"/><text x="44" y="${y+4}" text-anchor="end">${value>=10000?`${Number((value/10000).toFixed(1))}万`:value.toLocaleString('ja-JP')}</text>`;}
 months.forEach((m,i)=>{const x=83+i*80;for(const [j,type] of ['income','expense'].entries()){const height=m[type]/ceiling*172;svg+=`<rect x="${x+j*20}" y="${188-height}" width="14" height="${height}" rx="3" fill="${type==='income'?'#7ebbad':'#b4a1e0'}"><title>${m.key} ${type==='income'?'収入':'支出'} ${yen(m[type])}</title></rect>`;}svg+=`<text x="${x+17}" y="210" text-anchor="middle">${Number(m.key.slice(5))}月</text>`;});
 $('#flowChart').innerHTML=svg+'</svg>';
}
function renderCategories(list,total){
 let groups=grouped(list);if(groups.length>5)groups=[...groups.slice(0,4),['その他のカテゴリ',groups.slice(4).reduce((s,x)=>s+x[1],0)]];
 let start=0;const gradient=groups.map(([name,value],i)=>{const end=start+value/total*100;const segment=`${colors[i]} ${start}% ${end}%`;start=end;return segment;}).join(',');
 $('#categoryChart').innerHTML=`<div class="category-content"><div class="donut" style="background:${total?`conic-gradient(${gradient})`:'var(--track)'}" role="img" aria-label="支出合計 ${yen(total)}"><div class="donut-center"><small>支出合計</small><strong>${yen(total)}</strong></div></div><div class="category-list">${groups.length?groups.map(([name,value],i)=>`<div class="category-row" title="${escapeHtml(name)}：${yen(value)}（${(value/total*100).toFixed(1)}%）"><i style="background:${colors[i]}"></i><span class="cat-name">${escapeHtml(name)}</span><strong>${yen(value)}</strong></div>`).join(''):'<p class="muted">この月の支出は<br>まだありません。</p>'}</div></div>`;
}
function empty(filtered=false){return `<div class="empty-state">${icon('list')}<strong>${filtered?'条件に合う記録がありません':'この月の記録はまだありません'}</strong><p>${filtered?'検索語やカテゴリを変更してお試しください。':'最初の収支を追加して、お金の流れを見える化しましょう。'}</p>${filtered?'<button class="secondary-button" data-reset>条件をクリア</button>':'<button class="secondary-button" data-add>収支を追加</button>'}</div>`;}
function renderTable(target,list,filtered=false){
 if(!list.length){$(target).innerHTML=empty(filtered);return;}
 $(target).innerHTML=`<div class="table-scroll"><table><thead><tr><th scope="col">日付</th><th scope="col">内容</th><th scope="col" class="category-col">カテゴリ</th><th scope="col" class="num">金額</th><th scope="col" class="num">操作</th></tr></thead><tbody>${list.map(t=>`<tr><td class="date-cell">${escapeHtml(t.date.replaceAll('-',' / '))}</td><td><div class="transaction-name"><span class="type-icon ${t.type==='income'?'green':'purple'}">${icon(t.type==='income'?'down':'up')}</span>${t.hasImage?`<button class="transaction-photo-button" data-image="${t.id}" aria-label="${escapeHtml(t.title)}の画像を表示"><img src="${escapeHtml(t.imageUrl)}" alt=""></button>`:''}<div><strong title="${escapeHtml(t.title)}">${escapeHtml(t.title)}</strong>${t.note?`<small title="${escapeHtml(t.note)}">${escapeHtml(t.note)}</small>`:''}</div></div></td><td class="category-col"><span class="category-tag">${escapeHtml(t.category)}</span></td><td class="num amount ${t.type}">${t.type==='income'?'+':'−'}${yen(t.amount)}</td><td><div class="row-actions"><button data-edit="${t.id}" aria-label="${escapeHtml(t.title)}を編集" title="編集">${icon('edit')}</button><button data-delete="${t.id}" aria-label="${escapeHtml(t.title)}を削除" title="削除">${icon('trash')}</button></div></td></tr>`).join('')}</tbody></table></div>`;
}
function filteredEntries(){
 const query=$('#searchInput').value.trim().toLocaleLowerCase('ja'),type=$('#typeFilter').value,category=$('#categoryFilter').value,sort=$('#sortOrder').value;
 return currentEntries().filter(t=>(!query||`${t.title} ${t.note||''}`.toLocaleLowerCase('ja').includes(query))&&(!type||t.type===type)&&(!category||t.category===category)).sort((a,b)=>sort==='date-asc'?-newest(a,b):sort==='amount-desc'?b.amount-a.amount||newest(a,b):sort==='amount-asc'?a.amount-b.amount||newest(a,b):newest(a,b));
}
function renderLedger(){const list=filteredEntries(),pages=Math.max(1,Math.ceil(list.length/pageSize));page=Math.max(1,Math.min(page,pages));$('#filterCount').textContent=`${list.length}件の記録 · 収入 ${yen(sum(list,'income'))} ／ 支出 ${yen(sum(list,'expense'))}`;renderTable('#ledgerTable',list.slice((page-1)*pageSize,page*pageSize),!!($('#searchInput').value||$('#typeFilter').value||$('#categoryFilter').value));$('#pageInfo').textContent=list.length?`${(page-1)*pageSize+1}–${Math.min(page*pageSize,list.length)} / ${list.length}件`:'0件';$('#prevPage').disabled=page<=1;$('#nextPage').disabled=page>=pages;}
function reportRows(){const now=new Map(grouped(currentEntries())),before=new Map(grouped(transactions.filter(t=>t.date.startsWith(shiftMonth(selectedMonth,-1)))));return [...new Set([...now.keys(),...before.keys()])].map(name=>[name,now.get(name)||0,before.get(name)||0]).sort((a,b)=>b[1]-a[1]);}
function renderReport(){const list=currentEntries(),expense=sum(list,'expense'),before=sum(transactions.filter(t=>t.date.startsWith(shiftMonth(selectedMonth,-1))),'expense'),difference=expense-before,groups=grouped(list);$('#reportHighlights').innerHTML=`<article class="report-stat"><p>当月の支出</p><strong>${yen(expense)}</strong><small>${selectedMonth.replace('-','年')}月の合計</small></article><article class="report-stat"><p>前月からの支出増減</p><strong>${difference>0?'+':''}${yen(difference)}</strong><small>前月の支出 ${yen(before)}</small></article><article class="report-stat"><p>最も支出の多いカテゴリ</p><strong>${escapeHtml(groups[0]?.[0]||'—')}</strong><small>${groups.length?`${yen(groups[0][1])} · 全体の${(groups[0][1]/expense*100).toFixed(1)}%`:'支出の記録はありません'}</small></article>`;const rows=reportRows();$('#reportTable').innerHTML=rows.length?`<div class="table-scroll"><table><thead><tr><th>カテゴリ</th><th class="num">当月</th><th class="num">前月</th><th class="num">増減</th><th class="num">構成比</th></tr></thead><tbody>${rows.map(([name,now,prev])=>`<tr><td>${escapeHtml(name)}</td><td class="num">${yen(now)}</td><td class="num date-cell">${yen(prev)}</td><td class="num">${now>prev?'+':''}${yen(now-prev)}</td><td class="num">${expense?(now/expense*100).toFixed(1):'0.0'}%</td></tr>`).join('')}</tbody><tfoot><tr><th>合計</th><th class="num">${yen(expense)}</th><th class="num">${yen(before)}</th><th class="num">${difference>0?'+':''}${yen(difference)}</th><th class="num">${expense?'100.0':'0.0'}%</th></tr></tfoot></table></div>`:empty();}
const views={dashboard:['ダッシュボード','YOUR MONEY, AT A GLANCE','日々のお金の動きを、ひと目で。'],transactions:['収支台帳','EVERY TRANSACTION MATTERS','暮らしの記録を、きちんと整理。'],reports:['月次レポート','LOOK BACK, MOVE FORWARD','ひと月を振り返って、次の暮らしへ。'],settings:['設定・データ管理','MAKE YOURSELF AT HOME','見やすさと、大切なデータの管理。']};
function route(){const key=location.hash.slice(1) in views?location.hash.slice(1):'dashboard';Object.keys(views).forEach(v=>{$(`#${v}View`).hidden=v!==key;const link=$(`[data-view="${v}"]`);link.classList.toggle('is-active',v===key);if(v===key)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});$('#pageTitle').textContent=$('#breadcrumb').textContent=views[key][0];$('#pageEyebrow').textContent=views[key][1];$('#pageDescription').textContent=views[key][2];$('#periodToolbar').hidden=key==='settings';document.title=`${views[key][0]}｜tsumugi`;}
const form=$('#entryForm'),field=name=>form.elements.namedItem(name);
function fillCategories(value){const options=[...categories[field('type').value]];if(value&&!options.includes(value))options.push(value);field('category').innerHTML=options.map(c=>`<option>${escapeHtml(c)}</option>`).join('');if(value)field('category').value=value;}
function showImagePreview(src){$('#imagePreviewImg').src=src;$('#imagePreview').hidden=false;}
function openEntry(item){if(!loaded)return;form.reset();pendingImageData=null;removeExistingImage=false;$('#imagePreview').hidden=true;$('#imagePreviewImg').removeAttribute('src');field('id').value=item?.id||'';field('type').value=item?.type||'expense';fillCategories(item?.category);field('title').value=item?.title||'';field('amount').value=item?.amount||'';field('note').value=item?.note||'';field('date').value=item?.date||(selectedMonth===localDate().slice(0,7)?localDate():`${selectedMonth}-01`);if(item?.hasImage)showImagePreview(item.imageUrl);$('#dialogTitle').textContent=item?'収支を編集':'収支を追加';$('#formError').hidden=true;$('#entryDialog').showModal();field('title').focus();}
function setBusy(value,dialog){busy=value;dialog.querySelectorAll('button').forEach(b=>b.disabled=value);}
form.addEventListener('submit',async event=>{event.preventDefault();if(busy||!form.reportValidity())return;const data={userId:currentUserId,title:field('title').value.trim(),amount:Number(field('amount').value),type:field('type').value,category:field('category').value,date:field('date').value,note:field('note').value.trim()};if(pendingImageData)data.image=pendingImageData;else if(removeExistingImage)data.image=null;if(!data.title){$('#formError').textContent='内容を入力してください。';$('#formError').hidden=false;return;}const id=field('id').value;setBusy(true,$('#entryDialog'));$('#saveEntry').textContent='保存中…';$('#formError').hidden=true;try{const saved=await api(`/api/transactions${id?'/'+id:''}`,id?'PUT':'POST',data);transactions=transactions.filter(t=>t.id!==saved.id);transactions.push(saved);selectedMonth=saved.date.slice(0,7);page=1;render();$('#entryDialog').close();$('#syncStatus').textContent='保存済み · このパソコン';notify(id?'記録を更新しました':'収支を追加しました');}catch(error){$('#formError').textContent=error.message;$('#formError').hidden=false;}finally{setBusy(false,$('#entryDialog'));$('#saveEntry').textContent='保存する';}});
$('#imageInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!allowedImageTypes.includes(file.type)||file.size>maxImageBytes){event.target.value='';$('#formError').textContent=!allowedImageTypes.includes(file.type)?'画像はJPEG、PNG、WebP形式を選択してください。':'画像は5MB以内にしてください。';$('#formError').hidden=false;return;}const reader=new FileReader();reader.addEventListener('load',()=>{pendingImageData=reader.result;removeExistingImage=false;showImagePreview(reader.result);$('#formError').hidden=true;});reader.addEventListener('error',()=>{$('#formError').textContent='画像を読み取れませんでした。';$('#formError').hidden=false;});reader.readAsDataURL(file);});
$('#removeImage').addEventListener('click',()=>{pendingImageData=null;removeExistingImage=true;$('#imageInput').value='';$('#imagePreview').hidden=true;$('#imagePreviewImg').removeAttribute('src');});
form.querySelectorAll('[name=type]').forEach(r=>r.addEventListener('change',()=>fillCategories()));
$('#openEntry').addEventListener('click',()=>openEntry());
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.close&&!busy)$(`#${button.dataset.close}`).close();if(button.hasAttribute('data-add'))openEntry();if(button.hasAttribute('data-reset'))clearFilters();if(button.dataset.edit)openEntry(transactions.find(t=>t.id===Number(button.dataset.edit)));if(button.dataset.image){const item=transactions.find(t=>t.id===Number(button.dataset.image));$('#fullImage').src=item.imageUrl;$('#fullImage').alt=`${item.title}の画像`;$('#imageCaption').textContent=item.title;$('#imageDialog').showModal();}if(button.dataset.delete){pendingDelete=Number(button.dataset.delete);const item=transactions.find(t=>t.id===pendingDelete);$('#deleteDescription').textContent=`${item.title} / ${yen(item.amount)} / ${item.date}`;$('#deleteError').hidden=true;$('#deleteDialog').showModal();$('#deleteDialog [data-close]').focus();}});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(busy)e.preventDefault();}));
$('#confirmDelete').addEventListener('click',async()=>{if(busy||!pendingDelete)return;setBusy(true,$('#deleteDialog'));try{await api(`/api/transactions/${pendingDelete}?userId=${currentUserId}`,'DELETE');transactions=transactions.filter(t=>t.id!==pendingDelete);pendingDelete=null;render();$('#deleteDialog').close();notify('記録を削除しました');}catch(error){$('#deleteError').textContent=error.message;$('#deleteError').hidden=false;}finally{setBusy(false,$('#deleteDialog'));}});
function changeMonth(value){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(value)||value<'1900-01'||value>'9999-12'){$('#monthPicker').value=selectedMonth;return;}selectedMonth=value;page=1;if(loaded)render();else $('#monthPicker').value=value;}
$('#previousMonth').addEventListener('click',()=>changeMonth(shiftMonth(selectedMonth,-1)));$('#nextMonth').addEventListener('click',()=>changeMonth(shiftMonth(selectedMonth,1)));$('#currentMonth').addEventListener('click',()=>changeMonth(localDate().slice(0,7)));$('#monthPicker').addEventListener('change',e=>changeMonth(e.target.value));
['searchInput','typeFilter','categoryFilter','sortOrder'].forEach(id=>$(`#${id}`).addEventListener(id==='searchInput'?'input':'change',()=>{page=1;renderLedger();}));
function clearFilters(){['searchInput','typeFilter','categoryFilter'].forEach(id=>$(`#${id}`).value='');$('#sortOrder').value='date-desc';page=1;renderLedger();}
$('#clearFilters').addEventListener('click',clearFilters);$('#prevPage').addEventListener('click',()=>{page--;renderLedger();});$('#nextPage').addEventListener('click',()=>{page++;renderLedger();});
async function changeUser(value){const next=Number(value);if(userBusy||!users.some(user=>user.id===next)||next===currentUserId)return;const previous=currentUserId;userBusy=true;$('#userSwitcher').disabled=true;try{const entries=await api(`/api/transactions?userId=${next}`);currentUserId=next;transactions=entries;page=1;try{localStorage.setItem('tsumugi-user',String(next));}catch{}renderUsers();render();notify(`${currentUser().name}に切り替えました`);}catch(error){$('#userSwitcher').value=String(previous);notify(error.message);}finally{userBusy=false;$('#userSwitcher').disabled=false;}}
$('#userSwitcher').addEventListener('change',event=>changeUser(event.target.value));
$('#userForm').addEventListener('submit',async event=>{event.preventDefault();if(userBusy||!event.currentTarget.reportValidity())return;const input=event.currentTarget.elements.namedItem('userName'),name=input.value.trim();userBusy=true;event.currentTarget.querySelector('button').disabled=true;$('#userError').hidden=true;try{const user=await api('/api/users','POST',{name});users.push(user);input.value='';userBusy=false;await changeUser(user.id);renderUsers();notify(`${user.name}を追加しました`);}catch(error){$('#userError').textContent=error.message;$('#userError').hidden=false;}finally{userBusy=false;event.currentTarget.querySelector('button').disabled=false;}});
function exportCsv(rows,name){if(rows.length<2){notify('出力する記録がありません');return;}const cell=value=>{let s=String(value??'');if(typeof value==='string'&&/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('CSVファイルを出力しました');}
function exportEntries(list,suffix){exportCsv([['日付','区分','内容','カテゴリ','金額（円）','メモ'],...list.map(t=>[t.date,t.type==='income'?'収入':'支出',t.title,t.category,t.amount,t.note||''])],`tsumugi_${suffix}.csv`);}
$('#exportFiltered').addEventListener('click',()=>exportEntries(filteredEntries(),selectedMonth));$('#exportAll').addEventListener('click',()=>exportEntries([...transactions].sort(newest),'all_'+localDate()));$('#exportReport').addEventListener('click',()=>exportCsv([['カテゴリ','当月支出（円）','前月支出（円）','増減（円）'],...reportRows().map(([n,a,b])=>[n,a,b,a-b])],`tsumugi_report_${selectedMonth}.csv`));
function applySettings(){document.body.dataset.theme=$('#themeSetting').value;document.body.classList.toggle('compact-mode',$('#compactSetting').checked);}
try{$('#themeSetting').value=localStorage.getItem('tsumugi-theme')==='dark'?'dark':'light';$('#compactSetting').checked=localStorage.getItem('tsumugi-compact')==='true';}catch{}
['themeSetting','compactSetting'].forEach(id=>$(`#${id}`).addEventListener('change',()=>{applySettings();try{localStorage.setItem('tsumugi-theme',$('#themeSetting').value);localStorage.setItem('tsumugi-compact',$('#compactSetting').checked);}catch{notify('ブラウザの設定により表示設定を保存できませんでした');}}));
$('#todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());
$('#retryLoad').addEventListener('click',load);window.addEventListener('hashchange',route);applySettings();route();$('#monthPicker').value=selectedMonth;updateAvailability();load();
